Vagrant.configure("2") do |config|
  # Konfiguracja pierwszej maszyny
  config.vm.define "ansible-node01" do |node01|
    node01.vm.box = "generic/rocky8"
    #config.ssh.username = "bumipl"
    #config.ssh.password = "wkPqT!VqZ777"
    node01.vm.network "public_network", ip: "192.168.100.121"
    node01.vm.hostname = "ansible-node01"
    node01.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  # Konfiguracja drugiej maszyny
  config.vm.define "ansible-node02" do |node02|
    node02.vm.box = "generic/rocky8"
    node02.vm.network "public_network", ip: "192.168.100.122"
    node02.vm.hostname = "ansible-node02"
    node02.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

  end
end

