---
- name: Deploy Docker container with Apache2
  hosts: all
  become: true
  gather_facts: false
  vars:
    webroot: "/webroot/"
  tasks:
    - name: Install Docker on Debian
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Apache2 image
      community.docker.docker_image:
        name: httpd
        source: pull
        tag: latest

    - name: Create webroot directory
      ansible.builtin.file:
        path: "{{ webroot }}"
        state: directory

    - name: Copy index.html to webroot
      template:
        src: ./index.j2       
        dest: "{{ webroot }}index.html"

    - name: Run Apache2 container
      community.docker.docker_container:
        name: apache2-container
        image: httpd
        state: started
        detach: true
        exposed_ports:
          - 80
        ports:
          - "8080:80"
        volumes: "{{ webroot }}:/usr/local/apache2/htdocs/"

